packages:
  - slides/*/src

catalog:
  '@eslint/config-inspector': ^1.3.0
  '@iconify/json': ^2.2.386
  '@slidev/cli': ^52.2.4
  '@slidev/client': ^52.2.4
  '@slidev/theme-default': ^0.25.0
  '@types/node': ^24.5.2
  '@types/prompts': ^2.4.9
  '@types/seedrandom': ^3.0.8
  eslint: ^9.36.0
  eslint-config-flat-gitignore: ^2.1.0
  eslint-plugin-format: ^1.0.2
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-typegen: ^2.3.0
  execa: ^9.6.0
  fast-glob: ^3.3.3
  markdown-it-magic-link: ^0.1.4
  pnpm: ^10.17.1
  prettier-plugin-slidev: ^1.0.5
  prompts: ^2.4.2
  rimraf: ^6.0.1
  typescript: ^5.9.2
  unocss: ^66.5.1
  vue-router: ^4.5.1
  vue-tsc: ^3.0.8

onlyBuiltDependencies:
  - esbuild
  - vue-demi
