import fs from 'node:fs/promises' // Importing the file system module with promises
import { dirname, resolve } from 'node:path' // Importing path utilities
import process from 'node:process' // Importing process module
import fg from 'fast-glob' // Importing fast-glob for file pattern matching

const github_repo = "https://github.com/antfu/talks"
const talks_base_url = "https://markusritschel-talks.netlify.app"
const talks_overview_website = "https://antfu.me/talks"

// Finding all package.json files in the src directories of subdirectories
const packageFiles = (await fg('*/src/package.json', {
  onlyFiles: true,
})).sort()

// Extracting base URLs and PDF files from the package.json files
const bases = (await Promise.all(
  packageFiles.map(async (file) => {
    const talkRoot = dirname(dirname(file))
    const json = JSON.parse(await fs.readFile(file, 'utf-8'))
    const pdfFile = (await fg('*.pdf', {
      cwd: resolve(process.cwd(), talkRoot),
      onlyFiles: true,
    }))[0]
    const command = json.scripts?.build
    if (!command)
      return
    const base = command.match(/ --base (.*?)\s/)?.[1]  // base is the directory in which the slides are deployed
    if (!base)
      return
    return {
      dir: talkRoot,
      base,
      pdfFile,
    }
  }),
)).filter(Boolean) // Filtering out undefined values

// Generating redirects based on the extracted base URLs and PDF files
const redirects = bases
  .flatMap(({ dir, base, pdfFile }) => {
    const parts: string[] = []

    parts.push(`
[[redirects]]
from = "${dir}"
to = "${talks_base_url}${base}"
status = 301

[[redirects]]
from = "${base}src"
to = "${github_repo}/tree/main/${dir}"
status = 302`)

    if (pdfFile) {
      parts.push(`
[[redirects]]
from = "/${dir}/pdf"
to = "${github_repo}/blob/main/${dir}/${pdfFile}?raw=true"
status = 302

[[redirects]]
from = "${base}pdf"
to = "${github_repo}/blob/main/${dir}/${pdfFile}?raw=true"
status = 302`)
    }

    parts.push(`
[[redirects]]
from = "${base}*"
to = "${base}index.html"
status = 200
    `)
  
    return parts
  })
  .join('\n')

// Creating the content for the netlify.toml file
const content = `#
# This file is auto-generated by executing \`npm run update\` in the root.
#

[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"
PLAYWRIGHT_BROWSERS_PATH = "0"

${redirects}

[[redirects]]
from = "/"
to = "${talks_overview_website}"
status = 302
`

// Writing the content to the netlify.toml file
await fs.writeFile('netlify.toml', content, 'utf-8')
